Studi Kasus Project Data
Student Expense Analysis

Seorang mahasiswa ingin menganalisis pola pengeluarannya selama beberapa bulan untuk mengetahui kategori pengeluaran terbesar dan mengontrol keuangan pribadi.

Mahasiswa tersebut mencatat setiap pengeluaran harian ke dalam sebuah dataset yang berisi:

- tanggal pengeluaran
- kategori pengeluaran
- nominal pengeluaran

Kategori pengeluaran meliputi:

- Makanan
- Transportasi
- Internet
- Pendidikan
- Hiburan
- Belanja

1. Menampilkan Dataset

Program harus dapat membaca dan menampilkan data pengeluaran.

In [8]:
import pandas as pd

# Membaca data
df = pd.read_csv('expense_data.csv')

# Menampilkan data

df.sample(n=50, random_state=42)

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
30,2/19/2022 21:57,CUB - online payment,Food,NaN,Snacks,250.00,Expense,NaN,250.00,INR,250.00
126,1/6/2022 20:13,CUB - online payment,Food,NaN,Dinner with roommate,877.81,Expense,NaN,877.81,INR,877.81
220,12/7/2021 7:59,CUB - online payment,Food,NaN,Horlicks,15.00,Expense,NaN,15.00,INR,15.00
142,1/3/2022 22:15,CUB - online payment,Food,NaN,Dairy milk,10.00,Expense,NaN,10.00,INR,10.00
255,11/27/2021 13:46,CUB - online payment,Allowance,NaN,From dad,2000.00,Income,NaN,2000.00,INR,2000.00
236,12/3/2021 21:28,CUB - online payment,Food,NaN,Snack,40.00,Expense,NaN,40.00,INR,40.00
97,1/18/2022 20:54,CUB - online payment,Food,NaN,Dinner,301.15,Expense,NaN,301.15,INR,301.15
215,12/9/2021 8:47,CUB - online payment,Food,NaN,Breakfast with stu,110.00,Expense,NaN,110.00,INR,110.00
256,11/27/2021 9:33,CUB - online payment,Food,NaN,Breakfast,30.00,Expense,NaN,30.00,INR,30.00
144,1/3/2022 21:12,CUB - online payment,Other,NaN,From gpay,5.00,Income,NaN,5.00,INR,5.00
79,1/26/2022 16:52,CUB - online payment,Food,NaN,Paani poori,25.00,Expense,NaN,25.00,INR,25.00
208,12/11/2021 9:22,CUB - online payment,Allowance,NaN,From dad,1000.00,Income,NaN,1000.00,INR,1000.00
230,12/4/2021 20:20,CUB - online payment,Food,NaN,Snack,65.00,Expense,NaN,65.00,INR,65.00
101,1/18/2022 12:59,CUB - online payment,Other,NaN,From dad,1000.00,Income,NaN,1000.00,INR,1000.00
272,11/22/2021 14:16,CUB - online payment,Food,NaN,Dinner,90.00,Expense,NaN,90.00,INR,90.00
114,1/13/2022 17:47,CUB - online payment,Transportation,NaN,Rapido to pg,43.00,Expense,NaN,43.00,INR,43.00
193,12/18/2021 19:51,CUB - online payment,Social Life,NaN,Spiderman,363.72,Expense,NaN,363.72,INR,363.72
60,2/2/2022 20:14,CUB - online payment,Other,NaN,From dad,500.00,Income,NaN,500.00,INR,500.00
202,12/14/2021 23:54,CUB - online payment,Food,NaN,Lunch,40.00,Expense,NaN,40.00,INR,40.00
241,12/1/2021 14:00,CUB - online payment,Food,NaN,Lunch with company,160.00,Expense,NaN,160.00,INR,160.00
45,2/12/2022 14:47,CUB - online payment,Other,NaN,From dad,10000.00,Income,NaN,10000.00,INR,10000.00
73,1/27/2022 13:41,CUB - online payment,Other,NaN,To vishnu,100.00,Expense,NaN,100.00,INR,100.00
181,12/20/2021 19:23,CUB - online payment,Food,NaN,Milk with bharath,80.00,Expense,NaN,80.00,INR,80.00
165,12/27/2021 13:44,CUB - online payment,Other,NaN,From vicky,80.00,Income,NaN,80.00,INR,80.00
274,11/21/2021 17:07,CUB - online payment,Transportation,NaN,Rapido,130.00,Expense,NaN,130.00,INR,130.00
212,12/9/2021 20:03,CUB - online payment,Food,NaN,Snack with bharath,40.00,Expense,NaN,40.00,INR,40.00
84,1/24/2022 14:08,CUB - online payment,Food,NaN,Lunch with company,133.00,Expense,NaN,133.00,INR,133.00
42,2/12/2022 21:20,CUB - online payment,Food,NaN,Dinner with aravind and buddies,491.00,Expense,NaN,491.00,INR,491.00
9,2/27/2022 15:29,CUB - online payment,Food,NaN,Lunch,243.00,Expense,NaN,243.00,INR,243.00
118,1/11/2022 14:07,CUB - online payment,Food,NaN,Lunch with not preethi,135.50,Expense,NaN,135.50,INR,135.50
22,2/23/2022 12:38,CUB - online payment,Apparel,NaN,Earphone,399.00,Expense,NaN,399.00,INR,399.00
155,12/30/2021 13:36,CUB - online payment,Other,NaN,From kumara,30.00,Income,NaN,30.00,INR,30.00
24,2/21/2022 22:15,CUB - online payment,Transportation,NaN,It better be worth it,1300.00,Expense,NaN,1300.00,INR,1300.00
167,12/27/2021 12:33,CUB - online payment,Food,NaN,Coconut water with stu,50.00,Expense,NaN,50.00,INR,50.00
225,12/5/2021 19:45,CUB - online payment,Food,NaN,Milk with bharath,25.00,Expense,NaN,25.00,INR,25.00
75,1/27/2022 13:38,CUB - online payment,Other,NaN,From vicky,300.00,Income,NaN,300.00,INR,300.00
233,12/3/2021 21:59,CUB - online payment,Food,NaN,Milk with bharath,25.00,Expense,NaN,25.00,INR,25.00
262,11/26/2021 9:22,CUB - online payment,Food,NaN,Breakfast,60.00,Expense,NaN,60.00,INR,60.00
6,3/1/2022 18:21,CUB - online payment,Other,NaN,From dad,500.00,Income,NaN,500.00,INR,500.00
68,1/29/2022 14:44,CUB - online payment,Other,NaN,Sent to barath,100.00,Expense,NaN,100.00,INR,100.00
46,2/11/2022 22:41,CUB - online payment,Food,NaN,Dinner with aravind,373.00,Expense,NaN,373.00,INR,373.00
176,12/23/2021 16:31,CUB - online payment,Food,NaN,Lemon tea with company,15.00,Expense,NaN,15.00,INR,15.00
66,1/30/2022 12:28,CUB - online payment,Food,NaN,Brunch,105.00,Expense,NaN,105.00,INR,105.00
25,2/21/2022 16:06,CUB - online payment,Transportation,NaN,Travel to koyambedu,138.00,Expense,NaN,138.00,INR,138.00
125,1/6/2022 20:58,CUB - online payment,Food,NaN,Ketch up,20.00,Expense,NaN,20.00,INR,20.00
213,12/9/2021 14:01,CUB - online payment,Food,NaN,Lunch with company,280.00,Expense,NaN,280.00,INR,280.00
19,2/24/2022 19:15,CUB - online payment,Food,NaN,Tamen,324.70,Expense,NaN,324.70,INR,324.70
82,1/25/2022 9:20,CUB - online payment,Transportation,NaN,Train to vnr,325.00,Expense,NaN,325.00,INR,325.00
258,11/26/2021 20:57,CUB - online payment,Food,NaN,Snack,102.00,Expense,NaN,102.00,INR,102.00
269,11/24/2021 19:06,CUB - online payment,Transportation,NaN,Rapido,58.00,Expense,NaN,58.00,INR,58.00

2. Menghitung Total Pengeluaran

In [13]:
# Menghitung total berdasarkan tipe
total = df.groupby('Income/Expense')['INR'].sum()

# Mengambil nilai spesifik
total_income = total['Income']
total_expense = total['Expense']

print(f"Total Pendapatan (Income)  : INR {total_income:,.2f}")
print(f"Total Pengeluaran (Expense): INR {total_expense:,.2f}")
print(f"-----------------------------------------")
print(f"Sisa Saldo                : INR {total_income - total_expense:,.2f}")

Total Pendapatan (Income)  : INR 54,754.00
Total Pengeluaran (Expense): INR 59,024.00
-----------------------------------------
Sisa Saldo                : INR -4,270.00

In [18]:
# Menghitung total berdasarkan tipe
total = df.groupby('Income/Expense')['INR'].sum()

# Mengambil nilai spesifik
total_income = total['Income']
total_expense = total['Expense']

# Agar Income/Expense jadi kolom biasa, bukan index
laporan_df = total.reset_index()
laporan_df.index = laporan_df.index + 1

laporan_df

  Income/Expense      INR
1        Expense  59024.0
2         Income  54754.0

3. Analisis Per Kategori

In [24]:
# Menghitung total berdasarkan tipe
total = df.groupby('Category')['INR'].sum()

# Mengambil nilai spesifik
total_food = total['Food']
total_Transportation = total['Transportation']
total_Allowance = total['Allowance']
total_Apparel = total['Apparel']
total_SocialLife = total['Social Life']
total_Other = total['Other']

laporan_df = total.reset_index()
laporan_df.index = laporan_df.index + 1

laporan_df

            Category       INR
1          Allowance  14000.00
2            Apparel   3388.00
3             Beauty    196.00
4          Education   1400.00
5               Food  24502.48
6               Gift    115.00
7          Household  12188.00
8              Other  37868.00
9         Petty cash      3.00
10            Salary   8000.00
11  Self-development    400.00
12       Social Life   2513.72
13    Transportation   9203.80

4. Menampilkan Grafik

5. Menentukan Pengeluaran Terbesar